name: Node.js CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # 下方为我的工作流
    # 步骤1: 打包 Electron 应用程序
    - name: Install Electron Packager
      run: npm install electron-builder --save-dev

    - name: Publish to GitHub Releases
      env:
        GH_TOKEN : ${{secrets.GITHUB_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        publishingType: "release"
      run: npx electron-builder --publish always
    # 步骤2: 发布 Electron 应用程序
    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
